### ISSUE TITLE
Glob option "as" deprecated

### ISSUE THREAD

**Issue by SydneyOwl** [NisonChrist/md2neo4j-demo#1]
Hello @NisonChrist, 
Upon executing this project with the command `npm run dev` and subsequently clicking the download button within the browser, the terminal displays the following advisory message:
```sh
The glob option "as" has been deprecated in favour of "query". Please update `as: 'raw'` to `query: '?raw', import: 'default'`.
```
Additionally, there seems to be an excessive amount of console output. For clarity, we would prefer to attach a text file containing the console log. 
Here's the content in a file named 'md2cypher.txt'."
[md2cypher.txt](https://github.com/NisonChrist/md2neo4j/files/14767092/md2cypher.txt)

**Comment by NisonChrist** [comment]
Yes, it's just a demo working as an automation tool which is an alternative to writing Cypher code manually.

**Comment by SydneyOwl** [comment]
Sure! Markdown is a intermediate language!

**Comment by SydneyOwl** [comment]
![pexels-pixabay-357159 (1)](https://github.com/NisonChrist/md2neo4j-demo/assets/84191144/162ee18b-3521-4951-905d-2042061c299c)
